"""create rfy_content_buffer table

Revision ID: 4525947ce680
Revises: 6102cc9f6ab7
Create Date: 2025-07-10 20:22:28.339555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4525947ce680'
down_revision: Union[str, Sequence[str], None] = '6102cc9f6ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'rfy_content_buffer',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('source_id', sa.String(255), nullable=True),
        sa.Column('collection_name', sa.String(255), nullable=True),
        sa.Column('payload', sa.JSON(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rfy_content_buffer')
    # ### end Alembic commands ###
