"""create settings table

Revision ID: 7a8b9c0d1e2f
Revises: 4525947ce680
Create Date: 2025-01-27 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a8b9c0d1e2f'
down_revision: Union[str, Sequence[str], None] = '4525947ce680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'settings',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('key', sa.String(255), nullable=False, unique=True, index=True),
        sa.Column('value', sa.Text(), nullable=True),
    )
    # Insert default settings
    settings_table = sa.table(
        'settings',
        sa.column('key', sa.String),
        sa.column('value', sa.Text)
    )
    
    op.bulk_insert(settings_table, [
        {'key': 'ollama_url', 'value': 'http://ollama:11434'},
        {'key': 'default_collection_name', 'value': 'content'},
        {'key': 'vector_size', 'value': '4096'},
        {'key': 'llama_model', 'value': 'llama3:latest'},
        {'key': 'qdrant_host', 'value': 'qdrant'},
        {'key': 'qdrant_port', 'value': '6333'},
        {'key': 'rag_context_template', 'value': 'You are a helpful assistant. The user asked: \'{prompt}\'.\nHere is some relevant content that may help answer their question:\n{content_list}\nPlease answer the user\'s question using this context when relevant.'},
        {'key': 'rag_context_search_failed', 'value': 'You are a helpful assistant. The user asked: \'{prompt}\'.\n(Content search failed, so just answer as best as you can.)'},
        {'key': 'rag_context_no_results', 'value': 'You are a helpful assistant. The user asked: \'{prompt}\'.\nNo relevant content was found. Please answer as best as you can.'},
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###

