### Root Health Check
GET http://api.ragtify.local:8000/api/v1/

### API Health Endpoint
GET http://api.ragtify.local:8000:8000/api/v1/health

### Create Content Buffer Entry
POST http://api.ragtify.local:8000/api/v1/content/
Content-Type: application/json

{
  "source_id": "source-123",
  "collection_name": "default",
  "payload": {
  "url": "abc.com",
  "title": "yoga mat blue",
  "description": "6mm yoga mat"
}
}

### Process Content Buffer (all collections)
POST http://api.ragtify.local:8000/api/v1/content/process

### Process Content Buffer (specific collection)
POST http://api.ragtify.local:8000/api/v1/content/process?collection_name=default

### Search Content
POST http://api.ragtify.local:8000/api/v1/content/search
Content-Type: application/json

{
  "collection_name": "default",
  "query": "blue yoga mat",
  "limit": 3
}

### Chat with Content
POST http://api.ragtify.local:8000/api/v1/content/chat
Content-Type: application/json

{
  "model": "llama3:latest",
  "prompt": "What do we know about blue yoga mat",
  "collection_name": "default"
}

